jobs:
  test:
    executor: go/default
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run:
          name: Install Terraform 12
          command: |
            wget --quiet https://releases.hashicorp.com/terraform/0.12.20/terraform_0.12.20_linux_amd64.zip
            sudo unzip terraform_0.12.20_linux_amd64.zip -d /usr/local/bin
      - run:
          command: go test ~/project/test -v -timeout 45m
          no_output_timeout: 45m
          name: "go test"

      - run:
          name: Install Terraform 13
          command: |
            wget --quiet https://releases.hashicorp.com/terraform/0.13.6/terraform_0.13.6_linux_amd64.zip
            sudo unzip -o terraform_0.13.6_linux_amd64.zip -d /usr/local/bin
      - run:
          name: TF 13 Integration test
          command: go test ~/project/test -v -timeout 45m
          no_output_timeout: 45m

      - run:
          name: Install Terraform 14
          command: |
            wget --quiet https://releases.hashicorp.com/terraform/0.14.4/terraform_0.14.4_linux_amd64.zip
            sudo unzip -o terraform_0.14.4_linux_amd64.zip -d /usr/local/bin
      - run:
          name: TF 14 Integration test
          command: go test ~/project/test -v -timeout 45m
          no_output_timeout: 45m

orbs:
  go: circleci/go@0.2.0
version: 2.1
workflows:
  default:
    jobs:
      - test:
          context: aws-ci-1
  version: 2
